// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDBVXbxkZM09vGkX9P-7_7c6w6AnBJKM',
    appId: '1:414958453059:web:77d16f8133d7b31a38aff6',
    messagingSenderId: '414958453059',
    projectId: 'profesores-9471f',
    authDomain: 'profesores-9471f.firebaseapp.com',
    storageBucket: 'profesores-9471f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB738W90XO5hJO8wQmfi7XgoopMhP7cdMw',
    appId: '1:414958453059:android:5bc9dc4a80147c1938aff6',
    messagingSenderId: '414958453059',
    projectId: 'profesores-9471f',
    storageBucket: 'profesores-9471f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCahECGtWyIdshgr2RDedbN7Uu3CSibOms',
    appId: '1:414958453059:ios:71a2790dfddb661938aff6',
    messagingSenderId: '414958453059',
    projectId: 'profesores-9471f',
    storageBucket: 'profesores-9471f.appspot.com',
    iosBundleId: 'com.example.profesores1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCahECGtWyIdshgr2RDedbN7Uu3CSibOms',
    appId: '1:414958453059:ios:71a2790dfddb661938aff6',
    messagingSenderId: '414958453059',
    projectId: 'profesores-9471f',
    storageBucket: 'profesores-9471f.appspot.com',
    iosBundleId: 'com.example.profesores1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbDBVXbxkZM09vGkX9P-7_7c6w6AnBJKM',
    appId: '1:414958453059:web:87c764b58f10c9c338aff6',
    messagingSenderId: '414958453059',
    projectId: 'profesores-9471f',
    authDomain: 'profesores-9471f.firebaseapp.com',
    storageBucket: 'profesores-9471f.appspot.com',
  );
}
